export const CATEGORY_LABELS: Record<string, string> = {
  'conceptos-generales': 'Conceptos Generales',
  'rendimientos': 'Rendimientos',
  'deducciones': 'Deducciones',
  'procedimientos': 'Procedimientos',
  'inversiones': 'Inversiones',
  'autonomica': 'Autonómica',
  'autonomica-andalucia': 'Andalucía',
  'autonomica-aragon': 'Aragón',
  'autonomica-asturias': 'Asturias',
  'autonomica-illes-balears': 'Illes Balears',
  'autonomica-canarias': 'Canarias',
  'autonomica-cantabria': 'Cantabria',
  'autonomica-castilla-la-mancha': 'Castilla-La Mancha',
  'autonomica-castilla-y-leon': 'Castilla y León',
  'autonomica-cataluna': 'Cataluña',
  'autonomica-extremadura': 'Extremadura',
  'autonomica-galicia': 'Galicia',
  'autonomica-la-rioja': 'La Rioja',
  'autonomica-madrid': 'Comunidad de Madrid',
  'autonomica-murcia': 'Región de Murcia',
  'autonomica-comunitat-valenciana': 'Comunitat Valenciana',
  'autonomica-navarra': 'Navarra',
  'autonomica-pais-vasco': 'País Vasco',
  'fiscalidad-diferenciada': 'Fiscalidad Diferenciada',
  'sin_categoría': 'Sin Categoría',
}

export const CATEGORY_ORDER = [
  'conceptos-generales',
  'rendimientos',
  'deducciones',
  'procedimientos',
  'inversiones',
  'autonomica',
  'autonomica-andalucia',
  'autonomica-aragon',
  'autonomica-asturias',
  'autonomica-illes-balears',
  'autonomica-canarias',
  'autonomica-cantabria',
  'autonomica-castilla-la-mancha',
  'autonomica-castilla-y-leon',
  'autonomica-cataluna',
  'autonomica-extremadura',
  'autonomica-galicia',
  'autonomica-la-rioja',
  'autonomica-madrid',
  'autonomica-murcia',
  'autonomica-comunitat-valenciana',
  'autonomica-navarra',
  'autonomica-pais-vasco',
  'fiscalidad-diferenciada',
  'sin_categoría',
]
